### ISSUE TITLE
Issue when trying to run start:react-webapp

### ISSUE THREAD

**Issue by jferragut** [breatheco-de/breathecode-cli#10]
Attempting to run the new boiler on local (just installed the cli)

```
bc start:react-webapp

(node:38609) Warning: Mismatched version in bc-exercise-cli plugin manifest. Expected: 0.7.6 Received: 0.7.06
This usually means you have an oclif.manifest.json file that should be deleted in development. This file should be automatically generated when publishing.
 ›   Error: command start:react-webapp not found
```

**Comment by pandahacker** [comment]
Newest update pushed today that includes that functionality.

**Comment by jferragut** [comment]
@pandahacker do you know if they were merged?

**Comment by pandahacker** [comment]
This latest version has the react-webapp pushed to it. Does not have the validation if there are already files in the folder though.
https://www.npmjs.com/package/breathecode-cli/v/1.1.32 

![image](https://user-images.githubusercontent.com/2483918/47744948-e90d5d00-dc58-11e8-9f52-12b2e1504c45.png)

**Comment by jferragut** [comment]
@pandahacker Confirmed that with new install of CLI the ```breathecode start:react-webapp``` command is working. Great job, dude!

Closing this issue.
