### ISSUE TITLE
Accidental dependency "8"

### ISSUE THREAD

**Issue by tomwidmer** [breatheco-de/breathecode-cli#4]
Did you type `npm install 8` rather than `nvm install 8` by mistake?

**Comment by alesanchezr** [comment]
Where? probably it was ```nvm install 8``` but I don't know where you saw that.

**Comment by tomwidmer** [comment]
Here: https://github.com/breatheco-de/breathecode-cli/blob/master/package.json#L12

**Comment by alesanchezr** [comment]
Fixed.
