### ISSUE TITLE
Starting new project with -r when files are present

### ISSUE THREAD

**Issue by jferragut** [breatheco-de/breathecode-cli#7]
One of the issues we have experienced relates to beginning a project when files are already present in the workspace.

As a feature request, it may be better to add in a functionality that checks if there are other files present in the workspace when using the "-r" flag to install.

If files are present, prompt the user and ask if they want to delete the files before installing. Then if they say yes, the CLI would empty all files and directories recursively, before beginning the install.

Spoke with @alesanchezr  and he recommended posting on issue board.

**Comment by jferragut** [comment]
@alesanchezr  @pandahacker anything remaining on this, or can I close this issue out?

**Comment by alesanchezr** [comment]
nop. all good to me. I'm adding @pandahacker to the contributors readme.
